name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build-cache:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Nodejs
        uses: actions/setup-node@v1
        with:
          node-version: 16
          cahe: 'yarn'

      - name: Cache node modules and artifacts
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            /home/runner/.cache/Cypress/4.12.1/Cypress
            **/node_modules
          key: yarn-cache-${{ hashFiles('**/yarn.lock')}}

      - name: Install deps
        if: steps.yarn-cache.outputs.cache-hit != true
        run: yarn install
  test:
    needs: build-cache
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Nodejs
        uses: actions/setup-node@v1
        with:
          node-version: 16
          cahe: 'yarn'

      - name: Cache node modules and artifacts
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            /home/runner/.cache/Cypress/4.12.1/Cypress
            **/node_modules
          key: yarn-cache-${{ hashFiles('**/yarn.lock')}}

      - name: Install deps
        if: steps.yarn-cache.outputs.cache-hit != true
        run: yarn install

      - name: Run tests
        run: yarn test:ci

  lint:
    needs: build-cache
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Nodejs
        uses: actions/setup-node@v1
        with:
          node-version: 16
          cahe: 'yarn'

      - name: Cache node modules and artifacts
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            /home/runner/.cache/Cypress/4.12.1/Cypress
            **/node_modules
          key: yarn-cache-${{ hashFiles('**/yarn.lock')}}

      - name: Install deps
        if: steps.yarn-cache.outputs.cache-hit != true
        run: yarn install

      - name: Run linting
        run: yarn run lint:ci

  e2e:
    needs: build-cache
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Nodejs
        uses: actions/setup-node@v1
        with:
          node-version: 16
          cahe: 'yarn'

      - name: Cache node modules and artifacts
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            /home/runner/.cache/Cypress/4.12.1/Cypress
            **/node_modules
          key: yarn-cache-${{ hashFiles('**/yarn.lock')}}

      - name: Install deps
        if: steps.yarn-cache.outputs.cache-hit != true
        run: yarn install

      - name: Run end-to-end
        run: yarn run e2e
