# name of the workflow
name: CI 

# event trigger
on:
  pull_request:
    branches:
      - main

jobs:
  # each job runs on its own container
  build-and-cache: 
    # define type of machine your action will run on
    runs-on: ubuntu-latest
    # tell the machine what to do – steps
    steps:
      # give the step a name
      - name: Checkout
        # action to use for this step
        uses: actions/checkout@v2
        # parameters used for the action based on the documentation
        with:
         fetch-depth: 0

      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'

  # name of the job
  test:
    # define type of machine your action will run on
    needs: build-and-cache
    runs-on: ubuntu-latest
    # tell the machine what to do – steps
    steps:
      # give the step a name
      - name: Checkout
        # action to use for this step
        uses: actions/checkout@v2
        # parameters used for the action based on the documentation
        with:
         fetch-depth: 0

      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn' # if there's a cache hit in the container

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test:ci
  # => split single job into multiple jobs – less developer time but will take longer on GH actions
  lint:
    needs: build-and-cache
      # define type of machine your action will run on
    runs-on: ubuntu-latest
    # tell the machine what to do – steps
    steps:
      # give the step a name
      - name: Checkout
        # action to use for this step
        uses: actions/checkout@v2
        # parameters used for the action based on the documentation
        with:
         fetch-depth: 0

      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test:ci
      
      - name: Lint CI 
        run: yarn lint:ci
  e2e:
    needs: build-and-cache
    # define type of machine your action will run on
    runs-on: ubuntu-latest
    # tell the machine what to do – steps
    steps:
      # give the step a name
      - name: Checkout
        # action to use for this step
        uses: actions/checkout@v2
        # parameters used for the action based on the documentation
        with:
         fetch-depth: 0

      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Run e2e tests
        run: yarn e2e

